### ISSUE TITLE
Deployment succeeds, but it doesn't run

### ISSUE THREAD

**Issue by davidebbo** [wadewegner/azure-website-go-builder#1]
Not sure why, but it didn't work for me. My `web.config` has:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
        </handlers>
        <httpPlatform processPath="%HOME%\site\wwwroot\gopath\bin\20150107_231919.exe" 
                      startupTimeLimit="60">
        </httpPlatform>
    </system.webServer>
</configuration>
```

and the exe exists:

```
D:\home\site\wwwroot>dir %HOME%\site\wwwroot\gopath\bin\20150107_231919.exe
 Volume in drive D is Windows
 Volume Serial Number is 746D-E3BB

 Directory of D:\home\site\wwwroot\gopath\bin

01/07/2015  11:19 PM         5,161,472 20150107_231919.exe
               1 File(s)      5,161,472 bytes
               0 Dir(s)     520,646,656 bytes free
```

Yet all requests fail with a 500: `The page cannot be displayed because an internal server error has occurred.`

**Comment by davidebbo** [comment]
Oh, I see. The problem is that I installed the site extension, which has the xdt, and we don't want it here! So the instructions "_Or you can use the Go Lang for Azure Websites Extension_" are a bit misleading. :)

**Comment by wadewegner** [comment]
Doh! You are right. Apologies. Will update. Otherwise, it works?

**Comment by davidebbo** [comment]
Yes, seems to! I didn't try anything complex, but the site runs.

**Comment by davidebbo** [comment]
BTW, it can be made to work with the xdt by adding

```
<remove name="httpplatformhandler" />
```

before the `<add>` line. But then I think it'll blow up if you _don't_ have the xdt. :(

**Comment by wadewegner** [comment]
Done. Take a look at the [full tutorial](https://github.com/wadewegner/azure-website-go-builder).
