### ISSUE TITLE
Install go automatically when the app is deployed the first time

### ISSUE THREAD

**Issue by glennblock** [wadewegner/azure-website-go-builder#2]
Would be nice if go is automatically installed during deployment. This would allow users to just git push a .go file and everything is wired up for them in the cloud.

**Comment by wadewegner** [comment]
Agreed. My plan for this has been to use the site extension I've built and have people deploy using a resource manager script. Thoughts?

http://www.wadewegner.com/2015/01/creating-a-go-site-extension-and-resource-template-for-azure/

**Comment by wadewegner** [comment]
Take a look at the [new tutorial and steps](https://github.com/wadewegner/azure-website-go-builder). I think this is as easy as it gets until the Go bits are pre-deployed on the machine.
